apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mssql-green
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: mssql
        version: "latest"
    spec:
      containers:
        - name: mssql
          image: msql:latest
          ports:
            - name: http
              containerPort: 1433
